# Generated by Django 4.2.7 on 2023-11-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0002_pessoa_experiencia_profissional'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
